### ISSUE TITLE
new issue in new update :(

### ISSUE THREAD

**Issue by shubhamispro123** [vanhbakaa/moonbix-bot#13]
![Screenshot (91)](https://github.com/user-attachments/assets/fb2e103d-609e-4bea-a46b-01b144d33625)

**Comment by vanhbakaa** [comment]
fixed tell me if you still get this error in new version

**Comment by shubhamispro123** [comment]
![Screenshot (92)](https://github.com/user-attachments/assets/728875d2-fa08-428a-b5fd-eb3e25358fe4)
check bro issue
