### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by crispan2** [vanhbakaa/moonbix-bot#15]
`
![IMG_0798](https://github.com/user-attachments/assets/c015ab86-98d9-4d7a-a93f-5f7654123d32)
`

**Comment by crispan2** [comment]
![IMG_0798](https://github.com/user-attachments/assets/e4d6be51-fc40-46ca-8bdb-70cead552846)

**Comment by songshijun007** [comment]
me too

**Comment by syedsohail00** [comment]
I am also getting the same error

**Comment by groop30** [comment]
Me too

**Comment by vanhbakaa** [comment]
reduce in new version

**Comment by Inquisitor007** [comment]
Failed to complete game: 1727110430761|270.024|216.284|0.484|0|0|0|50|122;1727110433954|84.487|247.789|-0.998|304.364|261.785|0|50|95;1727110437476|162.323|220.065|0.119|130.799|482.919|2|60|90;1727110441323|204.434|233.433|0.407|105.180|456.378|0|30|137;1727110444049|80.587|242.602|0.136|0|0|0|7|11;1727110446706|114.805|233.620|0.017|110.935|466.021|1|60|43;1727110450266|150.295|224.517|-0.415|239.717|420.777|0|30|16;1727110453325|184.803|246.007|-0.507|0|0|2|46|87;1727110456272|168.653|206.949|-0.660|262.767|314.053|1|50|144;1727110459149|130.750|238.421|-0.572|338.076|535.626|1|50|139;1727110462192|252.725|228.029|0.818|0|0|0|54|154;1727110465842|88.421|225.380|-0.972|0|0|0|62|174;1727110469642|183.663|213.837|-0.983|378.707|250.500|1|30|65 Send this to me so i can fix it !

Failed to complete game: 1727110428138|204.484|238.168|0.260|163.142|391.604|0|30|5;1727110430915|103.555|200.919|-0.395|231.191|497.433|0|50|84;1727110433494|184.276|239.035|-0.644|341.108|425.298|2|60|120;1727110436789|121.336|241.071|-0.522|168.478|318.008|0|30|79;1727110439976|135.255|230.351|-0.973|0|0|1|1|7;1727110443307|273.871|224.116|0.217|0|0|1|67|178;1727110445907|237.677|243.575|-0.637|0|0|2|92|147;1727110455823|131.337|242.911|0.567|0|0|2|7|11;1727110464771|191.915|199.431|-0.038|197.924|356.131|1|30|198;1727110467702|137.382|245.181|0.016|134.464|429.525|1|70|54 Send this to me so i can fix it !

**Comment by vanhbakaa** [comment]
fixed
