### ISSUE TITLE
Error Failed to complete game:

### ISSUE THREAD

**Issue by NewsBee13** [vanhbakaa/moonbix-bot#16]
Hey, just wanted to let you know it still have this error

**Comment by vanhbakaa** [comment]
update new version

**Comment by NewsBee13** [comment]
nvm, its working, but why is the poin is very low, is it possible for user to set it like arround 100-200

**Comment by maxpaynew0w** [comment]
It's not working for me. One game was successful with 30 points, but the remaining five failed

**Comment by syedsohail00** [comment]
It is working after the update, but it is collecting very low points

**Comment by Inquisitor007** [comment]
Failed to complete game: 1727111837046|101.276|204.709|-0.593|298.790|473.140|1|60|5;1727111840491|105.191|236.532|-0.674|326.685|479.540|1|50|156;1727111843019|149.050|237.961|0.910|0|0|2|61|106;1727111846724|221.538|235.992|-0.879|306.419|282.034|1|70|91;1727111850680|245.901|236.202|-0.510|307.504|340.138|1|70|5;1727111854049|219.116|208.868|0.836|149.646|254.402|2|60|90 Send this to me so i can fix it !

**Comment by vanhbakaa** [comment]
Just use this version until i fix it tomorrow. Its late for me now

**Comment by maxpaynew0w** [comment]
This is from the updated version "Failed to complete game: 1727111414536|239.405|204.725|0.158|192.539|497.283|1|30|44;1727111418010|210.054|230.916|-0.847|374.230|334.026|1|60|30;1727111420845|270.437|236.655|-0.230|0|0|1|14|143;1727111423550|152.925|217.591|-0.647|385.574|491.784|1|50|12;1727111426124|76.152|206.605|-0.783|0|0|2|11|30;1727111429875|140.422|215.755|0.139|118.923|369.147|1|30|76 Send this to me so i can fix it !
Failed to complete game: 1727111467732|249.330|242.694|0.245|184.214|500.742|2|60|90;1727111470579|200.166|226.475|-0.473|0|0|2|95|57;1727111473914|156.154|243.317|0.377|0|0|0|27|60;1727111477746|272.490|220.118|-0.179|315.792|458.583|1|70|58;1727111481200|245.271|203.011|0.211|191.334|453.255|1|60|104 Send this to me so i can fix it !
Failed to complete game: 1727111519864|263.289|205.940|0.444|102.957|529.875|2|60|90 Send this to me so i can fix it !"  for troubleshooting

**Comment by Stockgolm** [comment]
Me too 
 Failed to complete game: 1727112247518|188.664|202.068|-0.496|322.791|436.762|1|50|101;1727112250021|261.066|238.293|0.792|154.916|320.248|0|30|111;1727112252795|256.371|234.552|-0.981|398.863|262.810|1|30|110 Send this to me so i can fix it !
 Failed to start game, msg: {'code': '116002', 'message': 'attempts not enough, user: 5746873400, resource code: moon-bix.', 'messageDetail': None, 'data': None, 'success': False}

**Comment by vanhbakaa** [comment]
fixed
