### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by hasan1818666891** [vanhbakaa/moonbix-bot#18]
Failed to complete game: 1727138949855|238.198|217.488|0.207|186.579|461.989|1|30|148;1727138952750|239.467|250.718|0.496|101.577|492.274|2|60|120;1727138955770|197.775|235.979|-0.642|0|0|0|78|149;1727138959550|177.032|217.920|-0.223|245.069|514.774|1|50|30 Send this to me so i can fix it !

Failed to complete game: 1727138953078|249.048|199.106|-0.707|333.935|283.991|1|70|81;1727138956916|254.192|231.777|-0.239|331.891|547.157|1|70|75 Send this to me so i can fix it !

Failed to complete game: 1727138959011|178.142|250.173|-0.770|394.798|429.796|1|30|67;1727138962034|216.659|212.524|-0.635|0|0|1|93|2;1727138965949|273.573|210.889|0.094|0|0|1|54|199;1727138968949|172.608|250.586|-0.999|246.676|253.460|1|50|84;1727138972924|272.942|233.510|0.476|159.453|443.434|0|30|94;1727138976711|138.183|237.305|-0.716|221.493|318.447|1|50|148 Send this to me so i can fix it !

1727138959799|228.627|221.422|0.158|0|0|1|57|97;1727138962985|134.838|209.465|-0.947|333.208|277.010|1|70|174;1727138965665|202.379|248.138|-0.824|347.206|347.598|2|60|120;1727138968259|203.998|241.829|0.458|0|0|0|1|165;1727138970893|255.929|227.563|-0.163|294.283|459.045|0|50|165;1727138973587|128.647|245.402|-0.234|201.208|547.193|1|70|155 Send this to me so i can fix it !

1727138966023|163.466|200.446|-0.634|349.772|427.828|1|70|85;1727138969808|167.028|202.320|0.165|127.343|440.254|1|70|118 Send this to me so i can fix it !

1727138968980|214.519|225.054|-0.342|283.742|415.289|1|50|72 Send this to me so i can fix it !

**Comment by vanhbakaa** [comment]
fixed
