### ISSUE TITLE
fix please

### ISSUE THREAD

**Issue by Tracker878** [vanhbakaa/moonbix-bot#19]
hello
i see send this to me 
WARNING  | 552 - 4ac4 | Failed to complete game: 1727140751281|184.890|226.143|-0.615|354.577|443.639|2|60|90;1727140754087|227.572|205.210|0.269|0|0|2|24|135;1727140757666|249.792|203.486|-0.232|314.824|476.022|1|60|59;1727140760493|200.875|220.927|-0.492|286.542|372.594|1|70|196 Send this to me so i can fix it !

WARNING  | 552 - 4ac4 | Failed to complete game: 1727140860225|192.632|246.080|-0.699|324.553|381.164|1|60|13;1727140864139|247.103|221.239|0.943|0|0|2|82|182;1727140866660|187.707|199.099|-0.147|226.670|461.481|1|70|123;1727140870187|186.458|208.467|-0.789|343.486|330.644|2|60|160;1727140873001|78.926|237.689|-0.533|177.477|394.085|1|30|118 Send this to me so i can fix it !

**Comment by vanhbakaa** [comment]
fixed
