### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by pnd3r** [vanhbakaa/moonbix-bot#29]
Stuck 

![image](https://github.com/user-attachments/assets/d01fb602-32b5-47c9-952a-0f64c76ab9de)

**Comment by vanhbakaa** [comment]
How long have you waited ?

**Comment by pnd3r** [comment]
> How long have you waited ?

About 30 minutes

**Comment by vanhbakaa** [comment]
> > How long have you waited ?
> 
> About 30 minutes

Check your api id and api hash or create a new one with another account
