### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by eloyEntony** [vanhbakaa/moonbix-bot#32]
Unknown error: HTTPSConnectionPool(host='www.binance.com', port=443): Max retries exceeded with url: /bapi/growth/v1/friendly/growth-paas/third-party/access/accessToken (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')))

how can fix?

**Comment by vanhbakaa** [comment]
set up a ssl for your pc
