### ISSUE TITLE
Just in case

### ISSUE THREAD

**Issue by Wapweb** [vanhbakaa/moonbix-bot#36]
Thanks for the script and effort. Just in case it would be interesting for somebody.

Devs added captcha, response for https://www.binance.com/bapi/growth/v1/friendly/growth-paas/mini-app-activity/third-party/game/start now looks like:

```
{'code': '000000', 'message': None, 'messageDetail': None, 'data': {'success': False, 'captchaType': 'bcaptcha2', 'needCaptchaVerification': True, 'securityCheckValidateId': '3385cf0d506b4f22a69609515369b1cf', 'sessionId': '3385cf0d506b4f22a69609515369b1cf'}, 'success': True}
```

**Comment by Wapweb** [comment]
![image](https://github.com/user-attachments/assets/1ef00e1c-37cc-4e5a-a7c7-4ca05b05a98b)
and if go to the bot and open using telegram now i got this

**Comment by Sameer515** [comment]
Yep same here i get same issue
