### ISSUE TITLE
ModuleNotFoundError: No module named 'bot.core.solver.captcha_solver'

### ISSUE THREAD

**Issue by bi-pixel** [vanhbakaa/moonbix-bot#44]
Traceback (most recent call last):
  File "/moonbix-bot/bot/core/tapper.py", line 800, in run
    await self.play_game(session)
  File "/moonbix-bot/bot/core/tapper.py", line 678, in play_game
    from bot.core.solver.captcha_solver import solve_captcha
ModuleNotFoundError: No module named 'bot.core.solver.captcha_solver'

**Comment by vanhbakaa** [comment]
what is your python version ?

**Comment by online** [comment]
@vanhbakaa my python version is 3.10.12. I have the same problem with the latest version of code.

**Comment by vanhbakaa** [comment]
![image](https://github.com/user-attachments/assets/b9b67ddb-ae23-4e6a-98bd-d4f341a40a57)
BRUH

**Comment by bi-pixel** [comment]
My python version is Python 3.11.5

```
root@b32d54318206:/moonbix-bot# python3 -V
Python 3.11.5
```

**Comment by vanhbakaa** [comment]
> My python version is Python 3.11.5
> 
> ```
> root@b32d54318206:/moonbix-bot# python3 -V
> Python 3.11.5
> ```

Let me check if it work on ubuntu server

**Comment by online** [comment]
@vanhbakaa 

I have also installed Python v3.11.5 on an Ubuntu server via pyenv. Then I ran the following commands:

```bash
rm -rf venv
python3 -m venv venv
source venv/bin/activate
pip3 install -r requirements.txt
```

But when I execute the command `python3 main.py`, I get the following error:

```bash
Traceback (most recent call last):
  File “/root/projects/moonbix-bot-original/main.py”, line 4, in <module>
    from bot.utils.launcher import process
  File “/root/projects/moonbix-bot-original/bot/utils/__init__.py”, line 1, in <module>
    from .logger import logger
  File “/root/projects/moonbix-bot-original/bot/utils/logger.py”, line 2, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'
```

Translated with DeepL.com (free version)

**Comment by online** [comment]
Also I have problem on my Mac with M2:

![CleanShot 2024-10-06 at 02 15 34@2x](https://github.com/user-attachments/assets/95794d0d-3046-47d7-b9f1-dc9727b32692)

**Comment by mz100814** [comment]
mac with m2 same problem
![image](https://github.com/user-attachments/assets/a283c392-02c2-4249-b8ed-30242d3c3d81)

**Comment by vanhbakaa** [comment]
> mac with m2 same problem ![image](https://private-user-images.githubusercontent.com/22016077/373914768-a283c392-02c2-4249-b8ed-30242d3c3d81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxOTMyNzgsIm5iZiI6MTcyODE5Mjk3OCwicGF0aCI6Ii8yMjAxNjA3Ny8zNzM5MTQ3NjgtYTI4M2MzOTItMDJjMi00MjQ5LWI4ZWQtMzAyNDJkM2MzZDgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDA1MzYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjODIzMDQ4NjMyMjI5YTk5NWNiODM1YTg0MzJmN2I0N2IwNDUwZTNkZDUyZDFmMWRhMThhY2NmYjE1NTA0NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L5-u6AoJ5Pnnwctf7HC0EAVYIKdEKpD8q9Uzbv8D__4)

fixed

**Comment by vanhbakaa** [comment]
> Also I have problem on my Mac with M2:
> 
> ![CleanShot 2024-10-06 at 02 15 34@2x](https://private-user-images.githubusercontent.com/722881/373912407-95794d0d-3046-47d7-b9f1-dc9727b32692.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxOTM1MDIsIm5iZiI6MTcyODE5MzIwMiwicGF0aCI6Ii83MjI4ODEvMzczOTEyNDA3LTk1Nzk0ZDBkLTMwNDYtNDdkNy1iOWYxLWRjOTcyN2IzMjY5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQwNTQwMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTFhMTU4MWEwZWY0NGNiMTFhYzZhYzc4Y2E3NjBhZDgzOGMzZWU4NDE1YjI3NTMyNTlhYmFlODI3NTY1YTZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.k9CEu0W8dFkOLBl9hTbOvD7eGykrswZlazURBYshP1M)

install newest version

**Comment by bi-pixel** [comment]
The new version works without this error. Thanks.
