### ISSUE TITLE
Massive error

### ISSUE THREAD

**Issue by Denys7814** [vanhbakaa/moonbix-bot#51]
I'm crying((

<img width="1146" alt="scrin1" src="https://github.com/user-attachments/assets/b4e15159-3965-4b6d-8b0b-9c3a2b4b3b7d">
<img width="1146" alt="scrin2" src="https://github.com/user-attachments/assets/a158219f-3ca5-4baf-a972-fac3924941d3">

I beg you, please help me solve this incredible problem!
Thanks.

**Comment by iamspa** [comment]
your certificate on your OS system need to update

**Comment by Denys7814** [comment]
> your certificate on your OS system need to update

Unfortunately, I did not find how to fix this! Can you please tell me how to do this?

**Comment by iamspa** [comment]
> > your certificate on your OS system need to update
> 
> Unfortunately, I did not find how to fix this! Can you please tell me how to do this?

change your DNS, because your DNS block connection to binance

**Comment by Denys7814** [comment]
> > > your certificate on your OS system need to update
> > 
> > 
> > Unfortunately, I did not find how to fix this! Can you please tell me how to do this?
> 
> change your DNS, because your DNS block connection to binance

Sorry, but how can I do this?)

**Comment by vanhbakaa** [comment]
Install a new ssl
