### ISSUE TITLE
Torch error

### ISSUE THREAD

**Issue by Quick1y8** [vanhbakaa/moonbix-bot#52]
![Screenshot_20241006_172727_Termux](https://github.com/user-attachments/assets/cc730b7d-b795-4852-95b0-bfe232fc2759)
What shoul i do?

**Comment by vanhbakaa** [comment]
Next time read readme.md before you ask bro
![image](https://github.com/user-attachments/assets/60737c2e-7f42-42dd-b13a-14dced0d7bfc)
