### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Quick1y8** [vanhbakaa/moonbix-bot#53]
![WhatsApp Görsel 2024-10-06 saat 17 41 55_68e8b0c9](https://github.com/user-attachments/assets/758bf666-1f16-4788-9d06-d74a7fe2cae2)

how to fix this?

**Comment by vanhbakaa** [comment]
Use correct python version

**Comment by Quick1y8** [comment]
> Use correct python version

It was working properly but all of a sudden this error showed up. What should I do?

**Comment by YinMoL** [comment]
> 使用正確的 python 版本
I get the same error
![螢幕擷取畫面 2024-10-08 105654](https://github.com/user-attachments/assets/f8b39d17-dbdb-4fe9-a0d9-725bf89cfd48)

**Comment by vanhbakaa** [comment]
> > 使用正確的 python 版本
> > I get the same error
> > ![螢幕擷取畫面 2024-10-08 105654](https://private-user-images.githubusercontent.com/109193715/374390787-f8b39d17-dbdb-4fe9-a0d9-725bf89cfd48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzODA4MDEsIm5iZiI6MTcyODM4MDUwMSwicGF0aCI6Ii8xMDkxOTM3MTUvMzc0MzkwNzg3LWY4YjM5ZDE3LWRiZGItNGZlOS1hMGQ5LTcyNWJmODljZmQ0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwOTQxNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jN2IzYzZjMmM5ZTkyMzAxMTg3MTEwMDkyNWE3OGFhODYzMzM2NDViNzc2NTExNDNmNjE5MGQ4NzNkNDg3YzM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Cnm9pIuUXQDFhS93yR63-TjS-wT7YenkaArFjW8Xe0E)

What platform are you running the bot on?

**Comment by Quick1y8** [comment]
tahnk you bro i fixed it.
