### ISSUE TITLE
 No module named 'bot.core.solver.captcha_solver'

### ISSUE THREAD

**Issue by SRS433** [vanhbakaa/moonbix-bot#54]
how can i fix this issue . please help me 

![Screenshot_1](https://github.com/user-attachments/assets/65379c81-b420-436b-97d1-34a740ad10b0)

**Comment by vanhbakaa** [comment]
Use correct python version

**Comment by SRS433** [comment]
> Use correct python version

thanks bro .i have multiple version of python on my pc . after i changed the python version as you said my issue fixed 👍

**Comment by danazor** [comment]
@SRS433 hey! got same problem. I use 3.10.x and i installed 3.11.5 too.

How did you changed the python version?
