### ISSUE TITLE
Encoded

### ISSUE THREAD

**Issue by RootXecution** [vanhbakaa/moonbix-bot#59]
I am a little suspicious about the captcha resolver because it is encoded. It might be a stealer.

**Comment by vanhbakaa** [comment]
I'm not force you to use my bot.

**Comment by vanhbakaa** [comment]
I just want to protect my hard work from copier

**Comment by online** [comment]
@vanhbakaa Can you somehow confirm that you're not really doing anything cheesy with your hidden code?

**Comment by vanhbakaa** [comment]
> @vanhbakaa Can you somehow confirm that you're not really doing anything cheesy with your hidden code?

If you're scared, just stop using the bot. I’ve worked hard on it. If it’s really unsafe, someone will report it here or on the Telegram channel. I have full contact info and a channel with over 1,000 subscribers.

**Comment by RootXecution** [comment]
> I just want to protect my hard work from copier

I appreciate it, I might not use it for security perspective as its not fully open source, but I appreciate your hard work. Keep it up
