### ISSUE TITLE
 | Unknown error: HTTPSConnectionPool(host='www.binance.com', port=443): Max retries exceeded with url: /bapi/growth/v1/friendly/growth-paas/third-party/access/accessToken (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:992)')))

### ISSUE THREAD

**Issue by faerhjio0gase** [vanhbakaa/moonbix-bot#62]
| Unknown error: HTTPSConnectionPool(host='www.binance.com', port=443): Max retries exceeded with url: /bapi/growth/v1/friendly/growth-paas/third-party/access/accessToken (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:992)')))

**Comment by vanhbakaa** [comment]
Join my tg channel for solution of this
