### ISSUE TITLE
Failed to solve captcha(default)

### ISSUE THREAD

**Issue by mz100814** [vanhbakaa/moonbix-bot#63]
![image](https://github.com/user-attachments/assets/8eb72468-858a-4538-9f31-a16af65bf3a8)

when tag is [default],the captcha solver will failed~

**Comment by mz100814** [comment]
after retry, always default~
![image](https://github.com/user-attachments/assets/216b0040-65ea-42c7-ab56-1e47cf132f5a)

**Comment by vanhbakaa** [comment]
Use a proxy from vietnam to solve it i mean you need to change ip
