### ISSUE TITLE
Risk Passed: True

### ISSUE THREAD

**Issue by Denys7814** [vanhbakaa/moonbix-bot#64]
<img width="739" alt="1" src="https://github.com/user-attachments/assets/d2e3d3c5-5573-47bc-b3ec-7df91ecf5ced">

1 - Is this how it should be?
2 - This is bad?

**Comment by vanhbakaa** [comment]
no it's good

it should be true, if it's False mean your account banned

**Comment by online** [comment]
@vanhbakaa Could you please tell me what "Qualified: False" means?

**Comment by Denys7814** [comment]
> no it's good
> 
> it should be true, if it's False mean your account banned

I understand. Thank you!

And what does "Qualified: True" mean?

**Comment by vanhbakaa** [comment]
If you qualified for the airdrop it will be true else it is False

**Comment by online** [comment]
> If you qualified for the airdrop it will be true else it is False

Okay, now I understand. The point is that you need to comply with the clause that is mentioned out in the rules of the moonbix game.

**Comment by Denys7814** [comment]
> If you qualified for the airdrop it will be true else it is False

Great! Thanks for the clarification.

It's just a pity that yesterday it stopped working completely, the captcha check doesn't work(
