### ISSUE TITLE
 Unknown error: No module named 'bot.core.s olver.captcha_solver'

### ISSUE THREAD

**Issue by ipinternet** [vanhbakaa/moonbix-bot#66]
Unknown error: No module named 'bot.core.s
olver.captcha_solver'

**Comment by thapld** [comment]
same, please fix

**Comment by vanhbakaa** [comment]
use correct python version as mention in readme.md

**Comment by seiyashun** [comment]
Dear @vanhbakaa 

I am using python 3.11.5 in PyCharm but still got this problem too. Can you help me to check this issue, thank you
![Screenshot 2024-10-31 at 08 29 20](https://github.com/user-attachments/assets/8717b53a-dab6-43e9-8be9-4f2f2407766e)
