### ISSUE TITLE
Captcha ERROR

### ISSUE THREAD

**Issue by Denys7814** [vanhbakaa/moonbix-bot#67]
![1](https://github.com/user-attachments/assets/162d4f51-ff97-456a-ab1d-e7f8209e5f71)

Recently, everything worked fine (October 10-11), but yesterday these problems started. Please help fix this!

**Comment by Denys7814** [comment]
> ![1](https://private-user-images.githubusercontent.com/79772023/376019796-162d4f51-ff97-456a-ab1d-e7f8209e5f71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MDg2MDMsIm5iZiI6MTcyODgwODMwMywicGF0aCI6Ii83OTc3MjAyMy8zNzYwMTk3OTYtMTYyZDRmNTEtZmY5Ny00NTZhLWFiMWQtZTdmODIwOWU1ZjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDA4MzE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxYjlkMWQxZjkyZThiODZjODdlODBmNDBiNDNlNjZiZjk3NDBlYzBmM2E3Y2VlYjk1MTE0YmI4YWY1ODg2ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gxTawuyAyh7TzG7t09U5qqARx0QlFl87VxbIVzyOB0c)
> 
> Recently, everything worked fine (October 10-11), but yesterday these problems started. Please help fix this!

I turned on and off "MORE_ACCURATE_CAPTCHA_SOLVER", it still did not help to solve this problem! The error remained, the program does not work(((

**Comment by vanhbakaa** [comment]
Just click done or turn off viruss protection

**Comment by Denys7814** [comment]
> Just click done or turn off viruss protection

Still the problem is not solved! I have already done this.
And on macos there is no antivirus protection and viruses too))

And why did it work for a couple of days at first, and then yesterday it stopped. I see in the chat many people started having similar problems yesterday and today.((

**Comment by Denys7814** [comment]
I fixed it. Thanks!
