### ISSUE TITLE
Unknown error while trying to get game data: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by cookie027** [vanhbakaa/moonbix-bot#7]
INFO     | 381 - | Sleep xs...
INFO     | 356 -  | Attempts left: 6
SUCCESS  | 364 -  | Game xx started successful
INFO     | 368 -  | Wait xs to complete the game...
ERROR    | 226 -  | Unknown error while trying to get game data: Expecting value: line 1 column 1 (char 0)

**Comment by shubhamispro123** [comment]
same

**Comment by vanhbakaa** [comment]
Im fixing it on sever stay tuned it will be fine next few hours

**Comment by oryhn** [comment]
Is it fixed bro .. me still face this problem

**Comment by syedsohail00** [comment]
I am facing the same issue

**Comment by vanhbakaa** [comment]
dont worrie i will fix tomorrow

**Comment by oryhn** [comment]
Ok bro ❤️ waiting

**Comment by vanhbakaa** [comment]
fixed
