### ISSUE TITLE
captcha 

### ISSUE THREAD

**Issue by xinyang520** [vanhbakaa/moonbix-bot#73]
Can you tell me how the verification code is passed? Can you provide code or examples

**Comment by ShiSheng** [comment]
> Can you tell me how the verification code is passed? Can you provide code or examples

you can see [this commit](https://github.com/vanhbakaa/moonbix-bot/commit/5b400f85b64aef48e55960eabb1df9c9f75ab9c2#diff-801cd8ad04d46a512ff0bc1c5bf4e73f312b5305073983a3e792383c26947b0fR24)
